spring.application.name=nutrition-voice-tracker-api

# Enforce flyway schema creation
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

# Spring datasource template
spring.datasource.url=jdbc:postgresql://localhost:5432/nutrition_tracker
spring.datasource.username=postgres
spring.datasource.password=CHANGEME

# Spring datasource overrides
spring.profiles.active=local